// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"es_ES": &dictionary{index: es_ESIndex, data: es_ESData},
		"ja_JP": &dictionary{index: ja_JPIndex, data: ja_JPData},
		"ko_KR": &dictionary{index: ko_KRIndex, data: ko_KRData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
		"zh_TW": &dictionary{index: zh_TWIndex, data: zh_TWData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"* Leave blank to record no log and delete the original log file.":  75,
	"* Support batch import, one link per line.":                        257,
	"* The following features may affect the stability of the service.": 122,
	"A selection is required.":                                          272,
	"About":                                                             15,
	"Absolute":                                                          88,
	"Add":                                                               27,
	"Admin":                                                             81,
	"Admin Address":                                                     82,
	"Advanced":                                                          114,
	"Advanced Options":                                                  95,
	"All":                                                               39,
	"All Files":                                                         3,
	"Allow Users":                                                       141,
	"An error occurred while checking for a software update.": 21,
	"Annotations": 131,
	"Another config already exists with the name \"%s\".":  51,
	"Are you sure you would like to delete config \"%s\"?": 54,
	"Are you sure you would like to delete proxy \"%s\"?":  251,
	"Are you sure you would like to disable proxy \"%s\"?": 253,
	"Are you sure you would like to stop config \"%s\"?":   218,
	"Assets":                 84,
	"Audience":               67,
	"Auth":                   62,
	"Auth Method":            63,
	"Authentication":         71,
	"Auto Delete":            87,
	"Bandwidth":              153,
	"Basic":                  57,
	"Behavior":               202,
	"Bind Address":           142,
	"Bind Port":              143,
	"Bind port is required.": 187,
	"Built on: %s":           2,
	"Cancel":                 24,
	"Certificate":            107,
	"Certificate Files":      5,
	"Certificate Key":        109,
	"Change Password":        227,
	"Check Interval":         182,
	"Check Timeout":          181,
	"Check Type":             180,
	"Check for updates":      18,
	"Checking for updates":   17,
	"Clear All":              29,
	"Client":                 152,
	"Common Only":            40,
	"Compression":            159,
	"Config already exists":  126,
	"Config already removed": 33,
	"Configuration":          30,
	"Configuration Files":    4,
	"Connection":             93,
	"Copy":                   214,
	"Copy Access Address":    248,
	"Copy Share Link":        46,
	"Create a Copy":          38,
	"Custom Domains":         147,
	"Custom domains and subdomain should have at least one of these set.": 197,
	"Days":     80,
	"Defaults": 232,
	"Define the default value when creating a new configuration.\nThe value here will not affect the existing configuration.": 233,
	"Delete":                        28,
	"Delete Date":                   90,
	"Delete Days":                   91,
	"Delete config \"%s\"":          53,
	"Delete proxy \"%s\"":           250,
	"Dial Timeout":                  96,
	"Direct Edit":                   246,
	"Disable":                       244,
	"Disable auto-start at boot":    118,
	"Disable custom first byte":     113,
	"Disable proxy \"%s\"":          252,
	"Domains":                       247,
	"Download":                      261,
	"Download updates":              16,
	"Edit":                          35,
	"Edit Client - %s":              56,
	"Edit Proxy - %s":               130,
	"Enable":                        254,
	"Encryption":                    158,
	"Enter Administration Password": 264,
	"Enter Password":                262,
	"Exit after login failure":      117,
	"Experimental Features":         121,
	"Export All Configs to ZIP":     47,
	"External Address":              203,
	"FRP Manager":                   256,
	"FRP version: %s":               1,
	"Failure Count":                 183,
	"Fallback":                      160,
	"Fallback Timeout":              161,
	"For FRP configuration documentation, please visit the FRP project page:": 20,
	"For comments or to report bugs, please visit the project page:":          19,
	"Group":                                  177,
	"Group Key":                              178,
	"HTTP File Server":                       243,
	"HTTP Password":                          167,
	"HTTP Proxy":                             124,
	"HTTP User":                              166,
	"Health Check":                           179,
	"Health check url is required.":          193,
	"Heart Beats":                            72,
	"Heartbeat":                              101,
	"Host Name":                              106,
	"Host Rewrite":                           168,
	"Idle Timeout":                           98,
	"Import Config":                          41,
	"Import Config from File":                32,
	"Import from Clipboard":                  44,
	"Import from File":                       42,
	"Import from URL":                        43,
	"Imported %d of %d configs.":             50,
	"Interval":                               102,
	"Invalid Input":                          266,
	"Invalid local port.":                    192,
	"Invalid remote port.":                   195,
	"Item":                                   200,
	"Keep Tunnel":                            157,
	"Keepalive":                              97,
	"Key Files":                              6,
	"Languages":                              228,
	"Latest":                                 199,
	"Level":                                  78,
	"Load Balance":                           176,
	"Local Address":                          138,
	"Local Directory":                        220,
	"Local Path":                             173,
	"Local Port":                             139,
	"Local address is required.":             189,
	"Local path is required.":                190,
	"Locations":                              148,
	"Log":                                    74,
	"Log File":                               76,
	"Log Files":                              7,
	"Log Level":                              239,
	"Log retention":                          240,
	"Manual Settings":                        49,
	"Master password":                        224,
	"Max Days":                               79,
	"Max Streams":                            100,
	"Metadata":                               120,
	"Multiplexer":                            150,
	"NAT Discovery":                          45,
	"NAT Type":                               201,
	"Name":                                   25,
	"New Client":                             55,
	"New Config":                             48,
	"New Configuration":                      31,
	"New Proxy":                              129,
	"New Version!":                           14,
	"New master password":                    236,
	"No":                                     205,
	"None":                                   64,
	"Not a number":                           12,
	"Number out of allowed range":            8,
	"OK":                                     23,
	"Off":                                    105,
	"On":                                     104,
	"Open Config":                            245,
	"Open File":                              36,
	"Open Log Folder":                        198,
	"Open Port":                              222,
	"Other Options":                          86,
	"Parameters":                             70,
	"Passive Port Range":                     255,
	"Password":                               83,
	"Password is set.":                       238,
	"Password mismatch":                      10,
	"Password removed.":                      235,
	"Please check and try again.":            11,
	"Please enter a number from %.f to %.f.": 267,
	"Please enter a number from %s to %s.":   268,
	"Please enter a number greater than %d.": 9,
	"Please enter a valid number.":           13,
	"Please enter the correct URL list.":     260,
	"Please select one of the provided options.": 271,
	"Plugin":                                 169,
	"Plugin Name":                            170,
	"Pool Count":                             99,
	"Port":                                   221,
	"Preferences":                            223,
	"Protocol":                               94,
	"Proxy Protocol":                         154,
	"Proxy already exists":                   184,
	"Public Network":                         206,
	"Quick Add":                              241,
	"Random":                                 132,
	"Re-enter password":                      237,
	"Ready":                                  259,
	"Relative":                               89,
	"Remote Address":                         213,
	"Remote Desktop":                         242,
	"Remote Port":                            140,
	"Rename automatically":                   258,
	"Request headers":                        149,
	"Requires local port or plugin.":         188,
	"Retry Count":                            163,
	"Retry Interval":                         165,
	"Role":                                   134,
	"Route User":                             151,
	"Running":                                208,
	"STUN Server":                            61,
	"Scope":                                  68,
	"Secret":                                 66,
	"Secret Key":                             137,
	"Select Certificate File":                108,
	"Select Certificate Key File":            110,
	"Select Log File":                        77,
	"Select Trusted CA File":                 112,
	"Select Unix Path":                       172,
	"Select a folder for directory listing.": 174,
	"Select a local directory that the admin server will load resources from.": 85,
	"Select language":                        231,
	"Selection Required":                     270,
	"Server":                                 135,
	"Server Address":                         58,
	"Server Name":                            144,
	"Server Port":                            59,
	"Server User":                            145,
	"Server name is required.":               186,
	"Service":                                216,
	"Set Defaults":                           234,
	"Show in Folder":                         37,
	"Source Address":                         115,
	"Start":                                  215,
	"Starting":                               210,
	"Status":                                 212,
	"Stop":                                   219,
	"Stop config \"%s\"":                     217,
	"Stopped":                                209,
	"Stopping":                               211,
	"Strip Prefix":                           175,
	"Subdomain":                              146,
	"TCP Mux":                                116,
	"The config \"%s\" already removed.":     34,
	"The config name \"%s\" already exists.": 127,
	"The current display language is":        229,
	"The file \"%s\" is not a valid ZIP file.":                                    52,
	"The number of local ports should be the same as the number of remote ports.": 196,
	"The password is incorrect. Re-enter password.":                               265,
	"The plugin does not support range ports.":                                    194,
	"The proxy name \"%s\" already exists.":                                       185,
	"The text does not match the required pattern.":                               269,
	"There are currently no updates available.":                                   22,
	"This feature only supports text in INI or TOML format.":                      249,
	"Timeout":         103,
	"Times/Hour":      164,
	"Token":           65,
	"Token Endpoint":  69,
	"Trusted CA":      111,
	"Type":            133,
	"UDP Packet Size": 125,
	"Unable to upgrade your config file due to proxy conversion failure, please check the proxy config and try again.\n\nBad proxy: %s": 128,
	"Unix Path":                     171,
	"Unix path is required.":        191,
	"Unknown":                       207,
	"Use legacy format config file": 119,
	"Use master password":           226,
	"Use server SVCB records":       123,
	"User":                          60,
	"Value":                         26,
	"Version: %s":                   0,
	"Visitor":                       136,
	"Work Conns":                    73,
	"Yes":                           204,
	"You can set a password to restrict access to this program.\nYou will be asked to enter it the next time you use this program.": 225,
	"You must enter an administration password to operate the %s.":                                                                  263,
	"You must restart program to apply the modification.":                                                                           230,
	"auto":    155,
	"default": 156,
	"ms":      162,
	"s":       92,
}

var en_USIndex = []uint32{ // 274 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000032,
	0x0000003c, 0x00000050, 0x00000062, 0x0000006c,
	0x00000076, 0x00000092, 0x000000bc, 0x000000ce,
	0x000000ea, 0x000000f7, 0x00000114, 0x00000121,
	0x00000127, 0x00000138, 0x0000014d, 0x0000015f,
	0x0000019e, 0x000001e6, 0x0000021e, 0x00000248,
	0x0000024b, 0x00000252, 0x00000257, 0x0000025d,
	0x00000261, 0x00000268, 0x00000272, 0x00000280,
	// Entry 20 - 3F
	0x00000292, 0x000002aa, 0x000002c1, 0x000002e5,
	0x000002ea, 0x000002f4, 0x00000303, 0x00000311,
	0x00000315, 0x00000321, 0x0000032f, 0x00000340,
	0x00000350, 0x00000366, 0x00000374, 0x00000384,
	0x0000039e, 0x000003a9, 0x000003b9, 0x000003da,
	0x0000040f, 0x00000439, 0x0000044f, 0x00000485,
	0x00000490, 0x000004a4, 0x000004aa, 0x000004b9,
	0x000004c5, 0x000004ca, 0x000004d6, 0x000004db,
	// Entry 40 - 5F
	0x000004e7, 0x000004ec, 0x000004f2, 0x000004f9,
	0x00000502, 0x00000508, 0x00000517, 0x00000522,
	0x00000531, 0x0000053d, 0x00000548, 0x0000054c,
	0x0000058d, 0x00000596, 0x000005a6, 0x000005ac,
	0x000005b5, 0x000005ba, 0x000005c0, 0x000005ce,
	0x000005d7, 0x000005de, 0x00000627, 0x00000635,
	0x00000641, 0x0000064a, 0x00000653, 0x0000065f,
	0x0000066b, 0x0000066d, 0x00000678, 0x00000681,
	// Entry 60 - 7F
	0x00000692, 0x0000069f, 0x000006a9, 0x000006b6,
	0x000006c1, 0x000006cd, 0x000006d7, 0x000006e0,
	0x000006e8, 0x000006eb, 0x000006ef, 0x000006f9,
	0x00000705, 0x0000071d, 0x0000072d, 0x00000749,
	0x00000754, 0x0000076b, 0x00000785, 0x0000078e,
	0x0000079d, 0x000007a5, 0x000007be, 0x000007d9,
	0x000007f7, 0x00000800, 0x00000816, 0x00000858,
	0x00000870, 0x0000087b, 0x0000088b, 0x000008a1,
	// Entry 80 - 9F
	0x000008c9, 0x0000094c, 0x00000956, 0x00000969,
	0x00000975, 0x0000097c, 0x00000981, 0x00000986,
	0x0000098d, 0x00000995, 0x000009a0, 0x000009ae,
	0x000009b9, 0x000009c5, 0x000009d1, 0x000009de,
	0x000009e8, 0x000009f4, 0x00000a00, 0x00000a0a,
	0x00000a19, 0x00000a23, 0x00000a33, 0x00000a3f,
	0x00000a4a, 0x00000a51, 0x00000a5b, 0x00000a6a,
	0x00000a6f, 0x00000a77, 0x00000a83, 0x00000a8e,
	// Entry A0 - BF
	0x00000a9a, 0x00000aa3, 0x00000ab4, 0x00000ab7,
	0x00000ac3, 0x00000ace, 0x00000add, 0x00000ae7,
	0x00000af5, 0x00000b02, 0x00000b09, 0x00000b15,
	0x00000b1f, 0x00000b30, 0x00000b3b, 0x00000b62,
	0x00000b6f, 0x00000b7c, 0x00000b82, 0x00000b8c,
	0x00000b99, 0x00000ba4, 0x00000bb2, 0x00000bc1,
	0x00000bcf, 0x00000be4, 0x00000c0b, 0x00000c24,
	0x00000c3b, 0x00000c5a, 0x00000c75, 0x00000c8d,
	// Entry C0 - DF
	0x00000ca4, 0x00000cb8, 0x00000cd6, 0x00000cff,
	0x00000d14, 0x00000d60, 0x00000da4, 0x00000db4,
	0x00000dbb, 0x00000dc0, 0x00000dc9, 0x00000dd2,
	0x00000de3, 0x00000de7, 0x00000dea, 0x00000df9,
	0x00000e01, 0x00000e09, 0x00000e11, 0x00000e1a,
	0x00000e23, 0x00000e2a, 0x00000e39, 0x00000e3e,
	0x00000e44, 0x00000e4c, 0x00000e60, 0x00000e94,
	0x00000e99, 0x00000ea9, 0x00000eae, 0x00000eb8,
	// Entry E0 - FF
	0x00000ec4, 0x00000ed4, 0x00000f51, 0x00000f65,
	0x00000f75, 0x00000f7f, 0x00000f9f, 0x00000fd3,
	0x00000fe3, 0x00000fec, 0x00001063, 0x00001070,
	0x00001082, 0x00001096, 0x000010a8, 0x000010b9,
	0x000010c3, 0x000010d1, 0x000010db, 0x000010ea,
	0x000010fb, 0x00001103, 0x0000110f, 0x0000111b,
	0x00001123, 0x00001137, 0x0000116e, 0x00001183,
	0x000011b8, 0x000011ce, 0x00001204, 0x0000120b,
	// Entry 100 - 11F
	0x0000121e, 0x0000122a, 0x00001255, 0x0000126a,
	0x00001270, 0x00001293, 0x0000129c, 0x000012ab,
	0x000012eb, 0x00001309, 0x00001337, 0x00001345,
	0x00001372, 0x0000139d, 0x000013cb, 0x000013de,
	0x00001409, 0x00001422,
} // Size: 1120 bytes

const en_USData string = "" + // Size: 5154 bytes
	"\x02Version: %[1]s\x02FRP version: %[1]s\x02Built on: %[1]s\x02All Files" +
	"\x02Configuration Files\x02Certificate Files\x02Key Files\x02Log Files" +
	"\x02Number out of allowed range\x02Please enter a number greater than %[" +
	"1]d.\x02Password mismatch\x02Please check and try again.\x02Not a number" +
	"\x02Please enter a valid number.\x02New Version!\x02About\x02Download up" +
	"dates\x02Checking for updates\x02Check for updates\x02For comments or to" +
	" report bugs, please visit the project page:\x02For FRP configuration do" +
	"cumentation, please visit the FRP project page:\x02An error occurred whi" +
	"le checking for a software update.\x02There are currently no updates ava" +
	"ilable.\x02OK\x02Cancel\x02Name\x02Value\x02Add\x02Delete\x02Clear All" +
	"\x02Configuration\x02New Configuration\x02Import Config from File\x02Con" +
	"fig already removed\x02The config \x22%[1]s\x22 already removed.\x02Edit" +
	"\x02Open File\x02Show in Folder\x02Create a Copy\x02All\x02Common Only" +
	"\x02Import Config\x02Import from File\x02Import from URL\x02Import from " +
	"Clipboard\x02NAT Discovery\x02Copy Share Link\x02Export All Configs to Z" +
	"IP\x02New Config\x02Manual Settings\x02Imported %[1]d of %[2]d configs." +
	"\x02Another config already exists with the name \x22%[1]s\x22.\x02The fi" +
	"le \x22%[1]s\x22 is not a valid ZIP file.\x02Delete config \x22%[1]s\x22" +
	"\x02Are you sure you would like to delete config \x22%[1]s\x22?\x02New C" +
	"lient\x02Edit Client - %[1]s\x02Basic\x02Server Address\x02Server Port" +
	"\x02User\x02STUN Server\x02Auth\x02Auth Method\x02None\x02Token\x02Secre" +
	"t\x02Audience\x02Scope\x02Token Endpoint\x02Parameters\x02Authentication" +
	"\x02Heart Beats\x02Work Conns\x02Log\x02* Leave blank to record no log a" +
	"nd delete the original log file.\x02Log File\x02Select Log File\x02Level" +
	"\x02Max Days\x02Days\x02Admin\x02Admin Address\x02Password\x02Assets\x02" +
	"Select a local directory that the admin server will load resources from." +
	"\x02Other Options\x02Auto Delete\x02Absolute\x02Relative\x02Delete Date" +
	"\x02Delete Days\x02s\x02Connection\x02Protocol\x02Advanced Options\x02Di" +
	"al Timeout\x02Keepalive\x02Idle Timeout\x02Pool Count\x02Max Streams\x02" +
	"Heartbeat\x02Interval\x02Timeout\x02On\x02Off\x02Host Name\x02Certificat" +
	"e\x02Select Certificate File\x02Certificate Key\x02Select Certificate Ke" +
	"y File\x02Trusted CA\x02Select Trusted CA File\x02Disable custom first b" +
	"yte\x02Advanced\x02Source Address\x02TCP Mux\x02Exit after login failure" +
	"\x02Disable auto-start at boot\x02Use legacy format config file\x02Metad" +
	"ata\x02Experimental Features\x02* The following features may affect the " +
	"stability of the service.\x02Use server SVCB records\x02HTTP Proxy\x02UD" +
	"P Packet Size\x02Config already exists\x02The config name \x22%[1]s\x22 " +
	"already exists.\x02Unable to upgrade your config file due to proxy conve" +
	"rsion failure, please check the proxy config and try again.\x0a\x0aBad p" +
	"roxy: %[1]s\x02New Proxy\x02Edit Proxy - %[1]s\x02Annotations\x02Random" +
	"\x02Type\x02Role\x02Server\x02Visitor\x02Secret Key\x02Local Address\x02" +
	"Local Port\x02Remote Port\x02Allow Users\x02Bind Address\x02Bind Port" +
	"\x02Server Name\x02Server User\x02Subdomain\x02Custom Domains\x02Locatio" +
	"ns\x02Request headers\x02Multiplexer\x02Route User\x02Client\x02Bandwidt" +
	"h\x02Proxy Protocol\x02auto\x02default\x02Keep Tunnel\x02Encryption\x02C" +
	"ompression\x02Fallback\x02Fallback Timeout\x02ms\x02Retry Count\x02Times" +
	"/Hour\x02Retry Interval\x02HTTP User\x02HTTP Password\x02Host Rewrite" +
	"\x02Plugin\x02Plugin Name\x02Unix Path\x02Select Unix Path\x02Local Path" +
	"\x02Select a folder for directory listing.\x02Strip Prefix\x02Load Balan" +
	"ce\x02Group\x02Group Key\x02Health Check\x02Check Type\x02Check Timeout" +
	"\x02Check Interval\x02Failure Count\x02Proxy already exists\x02The proxy" +
	" name \x22%[1]s\x22 already exists.\x02Server name is required.\x02Bind " +
	"port is required.\x02Requires local port or plugin.\x02Local address is " +
	"required.\x02Local path is required.\x02Unix path is required.\x02Invali" +
	"d local port.\x02Health check url is required.\x02The plugin does not su" +
	"pport range ports.\x02Invalid remote port.\x02The number of local ports " +
	"should be the same as the number of remote ports.\x02Custom domains and " +
	"subdomain should have at least one of these set.\x02Open Log Folder\x02L" +
	"atest\x02Item\x02NAT Type\x02Behavior\x02External Address\x02Yes\x02No" +
	"\x02Public Network\x02Unknown\x02Running\x02Stopped\x02Starting\x02Stopp" +
	"ing\x02Status\x02Remote Address\x02Copy\x02Start\x02Service\x02Stop conf" +
	"ig \x22%[1]s\x22\x02Are you sure you would like to stop config \x22%[1]s" +
	"\x22?\x02Stop\x02Local Directory\x02Port\x02Open Port\x02Preferences\x02" +
	"Master password\x02You can set a password to restrict access to this pro" +
	"gram.\x0aYou will be asked to enter it the next time you use this progra" +
	"m.\x02Use master password\x02Change Password\x02Languages\x02The current" +
	" display language is\x02You must restart program to apply the modificati" +
	"on.\x02Select language\x02Defaults\x02Define the default value when crea" +
	"ting a new configuration.\x0aThe value here will not affect the existing" +
	" configuration.\x02Set Defaults\x02Password removed.\x02New master passw" +
	"ord\x02Re-enter password\x02Password is set.\x02Log Level\x02Log retenti" +
	"on\x02Quick Add\x02Remote Desktop\x02HTTP File Server\x02Disable\x02Open" +
	" Config\x02Direct Edit\x02Domains\x02Copy Access Address\x02This feature" +
	" only supports text in INI or TOML format.\x02Delete proxy \x22%[1]s\x22" +
	"\x02Are you sure you would like to delete proxy \x22%[1]s\x22?\x02Disabl" +
	"e proxy \x22%[1]s\x22\x02Are you sure you would like to disable proxy " +
	"\x22%[1]s\x22?\x02Enable\x02Passive Port Range\x02FRP Manager\x02* Suppo" +
	"rt batch import, one link per line.\x02Rename automatically\x02Ready\x02" +
	"Please enter the correct URL list.\x02Download\x02Enter Password\x02You " +
	"must enter an administration password to operate the %[1]s.\x02Enter Adm" +
	"inistration Password\x02The password is incorrect. Re-enter password." +
	"\x02Invalid Input\x02Please enter a number from %.[1]f to %.[2]f.\x02Ple" +
	"ase enter a number from %[1]s to %[2]s.\x02The text does not match the r" +
	"equired pattern.\x02Selection Required\x02Please select one of the provi" +
	"ded options.\x02A selection is required."

var es_ESIndex = []uint32{ // 274 elements
	// Entry 0 - 1F
	0x00000000, 0x00000010, 0x00000024, 0x00000041,
	0x00000054, 0x0000006f, 0x00000087, 0x00000096,
	0x000000ab, 0x000000cd, 0x000000f1, 0x00000109,
	0x0000012e, 0x0000013c, 0x00000161, 0x00000171,
	0x00000177, 0x00000191, 0x000001ad, 0x000001c4,
	0x0000020e, 0x00000267, 0x000002a5, 0x000002d5,
	0x000002dd, 0x000002e6, 0x000002ed, 0x000002f7,
	0x000002ff, 0x00000306, 0x00000313, 0x00000322,
	// Entry 20 - 3F
	0x00000337, 0x0000035d, 0x00000379, 0x000003a3,
	0x000003aa, 0x000003ba, 0x000003d0, 0x000003e0,
	0x000003e6, 0x000003f2, 0x0000040a, 0x00000421,
	0x00000434, 0x00000450, 0x00000462, 0x0000047a,
	0x000004a3, 0x000004b0, 0x000004c1, 0x000004eb,
	0x00000520, 0x00000551, 0x00000571, 0x000005b1,
	0x000005bf, 0x000005d6, 0x000005de, 0x000005f6,
	0x00000609, 0x00000611, 0x0000061f, 0x00000624,
	// Entry 40 - 5F
	0x0000062c, 0x00000634, 0x0000063f, 0x00000647,
	0x00000651, 0x00000659, 0x0000066d, 0x00000679,
	0x00000688, 0x0000069d, 0x000006b2, 0x000006bb,
	0x0000071e, 0x00000732, 0x00000752, 0x00000758,
	0x00000767, 0x0000076d, 0x00000773, 0x0000077e,
	0x00000784, 0x0000078c, 0x000007ee, 0x000007fd,
	0x00000816, 0x0000081f, 0x00000828, 0x00000837,
	0x00000846, 0x00000848, 0x00000852, 0x0000085c,
	// Entry 60 - 7F
	0x0000086e, 0x00000880, 0x0000088a, 0x000008a0,
	0x000008b0, 0x000008c4, 0x000008d8, 0x000008e2,
	0x000008f0, 0x000008f9, 0x00000901, 0x00000916,
	0x00000922, 0x00000945, 0x0000095a, 0x00000986,
	0x00000996, 0x000009ba, 0x000009df, 0x000009e8,
	0x00000a00, 0x00000a08, 0x00000a36, 0x00000a63,
	0x00000a96, 0x00000aa0, 0x00000ac0, 0x00000b0e,
	0x00000b2f, 0x00000b3a, 0x00000b52, 0x00000b6e,
	// Entry 80 - 9F
	0x00000b9d, 0x00000c58, 0x00000c64, 0x00000c79,
	0x00000c85, 0x00000c8f, 0x00000c94, 0x00000c99,
	0x00000ca2, 0x00000cac, 0x00000cba, 0x00000ccb,
	0x00000cd8, 0x00000ce6, 0x00000cf8, 0x00000d0d,
	0x00000d1e, 0x00000d32, 0x00000d47, 0x00000d52,
	0x00000d6a, 0x00000d73, 0x00000d89, 0x00000d95,
	0x00000da5, 0x00000dad, 0x00000db9, 0x00000dc9,
	0x00000dce, 0x00000dda, 0x00000dea, 0x00000df2,
	// Entry A0 - BF
	0x00000dfe, 0x00000e07, 0x00000e1f, 0x00000e2b,
	0x00000e41, 0x00000e4c, 0x00000e63, 0x00000e70,
	0x00000e81, 0x00000e95, 0x00000e9e, 0x00000ea5,
	0x00000eaf, 0x00000eca, 0x00000ed5, 0x00000f0a,
	0x00000f1a, 0x00000f2e, 0x00000f34, 0x00000f43,
	0x00000f54, 0x00000f59, 0x00000f6d, 0x00000f77,
	0x00000f8a, 0x00000f9d, 0x00000fc3, 0x00000fea,
	0x0000100e, 0x00001033, 0x00001051, 0x00001069,
	// Entry C0 - DF
	0x00001083, 0x0000109c, 0x000010cb, 0x000010f6,
	0x00001110, 0x00001165, 0x000011bf, 0x000011ce,
	0x000011d6, 0x000011dc, 0x000011e8, 0x000011f7,
	0x0000120a, 0x0000120e, 0x00001211, 0x0000121e,
	0x0000122a, 0x00001231, 0x0000123a, 0x00001245,
	0x0000124c, 0x00001253, 0x00001265, 0x0000126c,
	0x00001275, 0x0000127e, 0x0000129d, 0x000012dc,
	0x000012e7, 0x000012f8, 0x000012ff, 0x0000130e,
	// Entry E0 - FF
	0x0000131b, 0x0000132f, 0x000013bf, 0x000013d8,
	0x000013ef, 0x000013f7, 0x0000141d, 0x00001457,
	0x0000146c, 0x0000147c, 0x000014f7, 0x00001506,
	0x0000151d, 0x00001537, 0x00001557, 0x00001579,
	0x0000158b, 0x000015a3, 0x000015b3, 0x000015c5,
	0x000015df, 0x000015ec, 0x00001601, 0x00001612,
	0x0000161b, 0x00001637, 0x0000166e, 0x00001685,
	0x000016bc, 0x000016d7, 0x00001710, 0x0000171a,
	// Entry 100 - 11F
	0x00001732, 0x00001747, 0x0000177e, 0x00001799,
	0x0000179f, 0x000017c4, 0x000017ce, 0x000017e8,
	0x0000182c, 0x00001856, 0x00001895, 0x000018a6,
	0x000018cd, 0x000018f2, 0x00001921, 0x00001936,
	0x00001965, 0x00001981,
} // Size: 1120 bytes

const es_ESData string = "" + // Size: 6529 bytes
	"\x02Versión: %[1]s\x02Versión FRP: %[1]s\x02Fecha de compilación: %[1]s" +
	"\x02Todos los archivos\x02Archivos de configuración\x02Archivos de certi" +
	"ficado\x02Archivos clave\x02Archivos de registro\x02Número fuera del ran" +
	"go permitido\x02Ingrese un número mayor que %[1]d.\x02Contraseña no coin" +
	"cide\x02Por favor revisa e intenta de nuevo.\x02No un número\x02Por favo" +
	"r ingrese un número valido.\x02Nueva versión!\x02Sobre\x02Descargar actu" +
	"alizaciones\x02Comprobando actualizaciones\x02Buscar actualizaciones\x02" +
	"Para comentarios o para informar errores, visite la página del proyecto:" +
	"\x02Para ver la documentación de configuración de FRP, visite la página " +
	"del proyecto FRP:\x02Se produjo un error al buscar una actualización de " +
	"software.\x02Actualmente no hay actualizaciones disponibles.\x02Aceptar" +
	"\x02Cancelar\x02Nombre\x02Valorizar\x02Agregar\x02Borrar\x02Limpiar todo" +
	"\x02Configuración\x02Nueva Configuración\x02Importar configuración desde" +
	" archivo\x02Configuración ya eliminada\x02La configuración \x22%[1]s\x22" +
	" ya se eliminó.\x02Editar\x02Abrir documento\x02Mostrar en la carpeta" +
	"\x02Crear una copia\x02Todos\x02Solo común\x02Importar configuración\x02" +
	"Importar desde archivo\x02Importar desde URL\x02Importar desde portapape" +
	"les\x02Detección de NAT\x02Copiar compartir enlace\x02Exportar todas las" +
	" configuraciones a ZIP\x02Nueva Config\x02Ajustes manuales\x02Importado " +
	"%[1]d de %[2]d configuraciones.\x02Ya existe otra configuración con el n" +
	"ombre \x22%[1]s\x22.\x02El archivo \x22%[1]s\x22 no es un archivo ZIP vá" +
	"lido.\x02Eliminar configuración \x22%[1]s\x22\x02¿Está seguro de que des" +
	"ea eliminar la configuración \x22%[1]s\x22?\x02Nuevo Cliente\x02Editar C" +
	"liente - %[1]s\x02Básico\x02Dirección del servidor\x02Puerto de servicio" +
	"\x02Usuario\x02Servidor STUN\x02Auth\x02Método\x02Ninguna\x02Simbólico" +
	"\x02Secreto\x02Audiencia\x02Alcance\x02Dirección de token\x02Parámetros" +
	"\x02Autenticación\x02Latidos del corazón\x02Conexión de trabajo\x02Regis" +
	"tro\x02* Déjelo en blanco para no registrar ningún registro y eliminar e" +
	"l archivo de registro original.\x02Archivo de registro\x02Seleccionar ar" +
	"chivo de registro\x02Nivel\x02Días máximos\x02Días\x02Admin\x02Dirección" +
	"\x02Clave\x02Recurso\x02Seleccione un directorio local desde el que el s" +
	"ervidor de administración cargará los recursos.\x02Otras opciones\x02Eli" +
	"minación automática\x02Absoluto\x02Relativo\x02Eliminar fecha\x02Elimina" +
	"r días\x02s\x02Conexión\x02Protocolo\x02Opciones Avanzada\x02Conexión ag" +
	"otado\x02Keepalive\x02Tiempo de inactividad\x02Conectar cuenta\x02Corrie" +
	"ntes máximas\x02Latido del corazón\x02Intervalo\x02Tiempo muerto\x02Ence" +
	"nder\x02Apagado\x02Nombre de anfitrión\x02Certificado\x02Seleccionar arc" +
	"hivo de certificado\x02Clave de certificado\x02Seleccionar archivo de cl" +
	"ave de certificado\x02CA de confianza\x02Seleccionar archivo CA de confi" +
	"anza\x02Desactivar primer byte personalizado\x02Avanzado\x02Dirección de" +
	" la fuente\x02Mux TCP\x02Salir después de fallar el inicio de sesión\x02" +
	"Desactivar el inicio automático al arrancar\x02Usar archivo de configura" +
	"ción de formato heredado\x02Metadatos\x02Características experimentales" +
	"\x02* Las siguientes características pueden afectar la estabilidad del s" +
	"ervicio.\x02Usar registros SVCB del servidor\x02Proxy HTTP\x02Tamaño del" +
	" paquete UDP\x02La configuración ya existe\x02El nombre de configuración" +
	" \x22%[1]s\x22 ya existe.\x02No se puede actualizar su archivo de config" +
	"uración debido a un error en la conversión del proxy. Verifique la confi" +
	"guración del proxy e inténtelo nuevamente.\x0a\x0aProxy incorrecto: %[1]" +
	"s\x02Nuevo Proxy\x02Editar Proxy - %[1]s\x02Anotaciones\x02Aleatorio\x02" +
	"Tipo\x02Role\x02Servidor\x02Visitante\x02Llave secreta\x02Dirección loca" +
	"l\x02Puerto local\x02Puerto remoto\x02Permitir usuarios\x02Dirección de " +
	"enlace\x02Puerto de enlace\x02Nombre del servidor\x02Usuario del servido" +
	"r\x02Subdominio\x02Dominios personalizados\x02Ruta URL\x02Solicitar enca" +
	"bezados\x02Multiplexor\x02Usuario de ruta\x02Cliente\x02Banda ancha\x02P" +
	"rotocolo proxy\x02auto\x02por defecto\x02Mantener túnel\x02Cifrado\x02Co" +
	"mpresión\x02Repuesto\x02Interruptor de respaldo\x02milisegundo\x02Número" +
	" de reintentos\x02Veces/Hora\x02Intervalo de reintento\x02Usuario HTTP" +
	"\x02Contraseña HTTP\x02Reescritura de host\x02Enchufar\x02Nombre\x02Ruta" +
	" Unix\x02Seleccione la ruta de Unix\x02Ruta local\x02Seleccione una carp" +
	"eta para la lista de directorios.\x02Prefijo de tira\x02Equilibrio de ca" +
	"rga\x02Grupo\x02Clave de grupo\x02Chequeo de salud\x02Tipo\x02Se acabó e" +
	"l tiempo\x02Intervalo\x02Recuento de fallas\x02El proxy ya existe\x02El " +
	"nombre de proxy \x22%[1]s\x22 ya existe.\x02El nombre del servidor es ob" +
	"ligatorio.\x02Se requiere puerto de vinculación.\x02Requiere puerto loca" +
	"l o complemento.\x02Se requiere dirección local.\x02Se requiere ruta loc" +
	"al.\x02Se requiere la ruta Unix.\x02Puerto local no válido.\x02Se requie" +
	"re la URL de verificación de estado.\x02El complemento no admite puertos" +
	" de rango.\x02Puerto remoto no válido.\x02La cantidad de puertos locales" +
	" debe ser la misma que la cantidad de puertos remotos.\x02Los dominios y" +
	" subdominios personalizados deben tener al menos uno de estos configurad" +
	"os.\x02Abrir registro\x02Último\x02Ítem\x02Tipo de NAT\x02Comportamiento" +
	"\x02Dirección externa\x02Sí\x02No\x02Red pública\x02Desconocido\x02Corre" +
	"r\x02Detenido\x02Comenzando\x02Parada\x02Estado\x02Dirección remota\x02C" +
	"opiar\x02Comienzo\x02Servicio\x02Detener configuración \x22%[1]s\x22\x02" +
	"¿Está seguro de que desea detener la configuración \x22%[1]s\x22?\x02De" +
	"téngase\x02Directorio local\x02Puerto\x02Puerto abierto\x02Preferencias" +
	"\x02Contraseña maestra\x02Puede establecer una contraseña para restringi" +
	"r el acceso a este programa.\x0aSe le pedirá que lo ingrese la próxima v" +
	"ez que use este programa.\x02Usar contraseña maestra\x02Cambiar la contr" +
	"aseña\x02Idiomas\x02El idioma de visualización actual es\x02Debe reinici" +
	"ar el programa para aplicar la modificación.\x02Seleccione el idioma\x02" +
	"Predeterminados\x02Defina el valor predeterminado al crear una nueva con" +
	"figuración.\x0aEl valor aquí no afectará la configuración existente.\x02" +
	"Valor ajustado\x02Contraseña eliminada.\x02Nueva contraseña maestra\x02E" +
	"scriba la contraseña otra vez\x02La contraseña está configurada.\x02Nive" +
	"l de registro\x02Retención de registros\x02Añadir rápido\x02Escritorio r" +
	"emoto\x02Servidor de archivos HTTP\x02Deshabilitar\x02Abrir configuració" +
	"n\x02Edición directa\x02Dominios\x02Copiar dirección de acceso\x02Esta f" +
	"unción solo admite texto en formato INI o TOML.\x02Eliminar proxy \x22%[" +
	"1]s\x22\x02¿Está seguro de que desea eliminar el proxy \x22%[1]s\x22?" +
	"\x02Deshabilitar proxy \x22%[1]s\x22\x02¿Está seguro de que desea desact" +
	"ivar el proxy \x22%[1]s\x22?\x02Habilitar\x02Gama de puertos pasivos\x02" +
	"Administrador de FRP\x02* Admite importación por lotes, un enlace por lí" +
	"nea.\x02Renombrar automáticamente\x02Listo\x02Introduzca la lista de URL" +
	" correcta.\x02Descargar\x02Introducir la contraseña\x02Debe ingresar una" +
	" contraseña de administración para operar %[1]s.\x02Ingrese la contraseñ" +
	"a de administración\x02La contraseña es incorrecta. Escriba la contraseñ" +
	"a otra vez.\x02Entrada invalida\x02Ingrese un número de %.[1]f a %.[2]f." +
	"\x02Ingrese un número de %[1]s a %[2]s.\x02El texto no coincide con el p" +
	"atrón requerido.\x02Selección requerida\x02Seleccione una de las opcione" +
	"s proporcionadas.\x02Se requiere una selección."

var ja_JPIndex = []uint32{ // 274 elements
	// Entry 0 - 1F
	0x00000000, 0x00000018, 0x00000034, 0x0000004f,
	0x00000068, 0x0000007b, 0x00000091, 0x000000a7,
	0x000000ba, 0x000000d3, 0x0000010d, 0x00000129,
	0x00000151, 0x0000016d, 0x0000019b, 0x000001b7,
	0x000001bb, 0x000001d7, 0x000001f3, 0x00000209,
	0x00000279, 0x000002eb, 0x00000340, 0x00000380,
	0x00000383, 0x00000393, 0x0000039a, 0x0000039e,
	0x000003a5, 0x000003ac, 0x000003bf, 0x000003c6,
	// Entry 20 - 3F
	0x000003d6, 0x00000407, 0x00000432, 0x00000468,
	0x0000046f, 0x00000485, 0x0000049b, 0x000004b4,
	0x000004bb, 0x000004ce, 0x000004e7, 0x00000509,
	0x00000522, 0x0000054d, 0x00000558, 0x00000574,
	0x000005a2, 0x000005b2, 0x000005bf, 0x00000600,
	0x00000645, 0x00000692, 0x000006ad, 0x000006e7,
	0x00000703, 0x00000727, 0x0000072e, 0x00000747,
	0x0000075a, 0x00000767, 0x00000778, 0x0000077f,
	// Entry 40 - 5F
	0x0000078c, 0x00000793, 0x000007a0, 0x000007aa,
	0x000007b4, 0x000007bb, 0x000007ce, 0x000007e1,
	0x000007e8, 0x000007f8, 0x00000805, 0x0000080c,
	0x00000875, 0x00000888, 0x000008a4, 0x000008ae,
	0x000008bb, 0x000008bf, 0x000008c9, 0x000008df,
	0x000008ef, 0x000008f6, 0x0000095d, 0x00000973,
	0x00000980, 0x00000987, 0x0000098e, 0x00000998,
	0x000009a5, 0x000009a7, 0x000009ae, 0x000009be,
	// Entry 60 - 7F
	0x000009d7, 0x000009f0, 0x00000a00, 0x00000a1f,
	0x00000a35, 0x00000a4b, 0x00000a5e, 0x00000a65,
	0x00000a78, 0x00000a7f, 0x00000a86, 0x00000a93,
	0x00000a9d, 0x00000abc, 0x00000acc, 0x00000afa,
	0x00000b0d, 0x00000b3f, 0x00000b70, 0x00000b77,
	0x00000b8d, 0x00000b97, 0x00000bb6, 0x00000be1,
	0x00000c15, 0x00000c25, 0x00000c38, 0x00000c95,
	0x00000cc1, 0x00000cd3, 0x00000cec, 0x00000d0e,
	// Entry 80 - 9F
	0x00000d41, 0x00000e0e, 0x00000e24, 0x00000e42,
	0x00000e49, 0x00000e56, 0x00000e60, 0x00000e67,
	0x00000e71, 0x00000e7e, 0x00000e88, 0x00000ea1,
	0x00000eb7, 0x00000ecd, 0x00000ee9, 0x00000f02,
	0x00000f18, 0x00000f28, 0x00000f41, 0x00000f54,
	0x00000f6d, 0x00000f84, 0x00000fa0, 0x00000fb6,
	0x00000fcc, 0x00000fdf, 0x00000fe9, 0x00001005,
	0x0000100c, 0x00001016, 0x00001032, 0x0000103c,
	// Entry A0 - BF
	0x00001043, 0x0000104a, 0x00001072, 0x0000107c,
	0x0000108f, 0x0000109a, 0x000010aa, 0x000010bc,
	0x000010d1, 0x000010ea, 0x000010fa, 0x0000110d,
	0x00001119, 0x0000112e, 0x00001141, 0x00001181,
	0x000011a0, 0x000011ad, 0x000011ba, 0x000011d0,
	0x000011dd, 0x000011e7, 0x000011fa, 0x0000120d,
	0x00001217, 0x0000123f, 0x00001278, 0x0000129a,
	0x000012c2, 0x00001302, 0x0000132d, 0x00001352,
	// Entry C0 - DF
	0x00001370, 0x00001398, 0x000013c6, 0x0000140c,
	0x00001434, 0x0000149a, 0x00001529, 0x00001545,
	0x0000154c, 0x00001553, 0x00001561, 0x00001568,
	0x0000157b, 0x00001582, 0x0000158c, 0x000015a8,
	0x000015b8, 0x000015c8, 0x000015cf, 0x000015d6,
	0x000015dd, 0x000015e4, 0x000015fd, 0x00001607,
	0x00001611, 0x0000161e, 0x00001642, 0x0000167c,
	0x00001686, 0x00001693, 0x0000169d, 0x000016ad,
	// Entry E0 - FF
	0x000016ba, 0x000016d6, 0x00001792, 0x000017bd,
	0x000017dc, 0x000017e3, 0x000017fc, 0x00001854,
	0x0000186a, 0x0000187a, 0x00001909, 0x00001922,
	0x0000194d, 0x00001972, 0x0000197c, 0x000019aa,
	0x000019ba, 0x000019c7, 0x000019da, 0x000019f9,
	0x00001a17, 0x00001a1e, 0x00001a2e, 0x00001a3b,
	0x00001a4b, 0x00001a70, 0x00001acc, 0x00001af6,
	0x00001b36, 0x00001b60, 0x00001ba3, 0x00001baa,
	// Entry 100 - 11F
	0x00001bc6, 0x00001bda, 0x00001c39, 0x00001c55,
	0x00001c5c, 0x00001c90, 0x00001ca3, 0x00001cc2,
	0x00001d1d, 0x00001d3f, 0x00001d89, 0x00001d96,
	0x00001dd9, 0x00001e1a, 0x00001e57, 0x00001e64,
	0x00001eb0, 0x00001ec9,
} // Size: 1120 bytes

const ja_JPData string = "" + // Size: 7881 bytes
	"\x02バージョン：%[1]s\x02FRP バージョン：%[1]s\x02コンパイル日：%[1]s\x02すべてのファイル\x02設定ファイル" +
	"\x02証明書ファイル\x02秘密鍵ファイル\x02ログファイル\x02許容範囲外の数値\x02%[1]d より大きい数値を入力してください。" +
	"\x02パスワードの不一致\x02もう一度確認してください。\x02数字ではありません\x02有効な数値を入力してください。\x02新しいバージ" +
	"ョン！\x02約\x02更新をダウンロード\x02アップデートの確認\x02更新を確認する\x02コメントやバグの報告については、プロジェク" +
	"トページにアクセスしてください：\x02FRP 設定ドキュメントについては、FRP プロジェクトページにアクセスしてください：\x02ソフト" +
	"ウェアアップデートの確認中にエラーが発生しました。\x02現在、利用可能なアップデートはありません。\x02OK\x02キャンセル\x02名" +
	"前\x02値\x02追加\x02削除\x02すべてクリア\x02設定\x02新しい設定\x02ファイルから設定をインポートする\x02設定は" +
	"すでに削除されています\x02設定「%[1]s」は既に削除されています。\x02編集\x02ファイルを開く\x02フォルダで見て\x02コピ" +
	"ーを作成する\x02全て\x02共通設定のみ\x02設定のインポート\x02ファイルからインポート\x02URLからインポート\x02クリッ" +
	"プボードからインポート\x02NAT 検出\x02共有リンクをコピー\x02すべての設定をZIPにエクスポート\x02新しい設定\x02手動" +
	"設定\x14\x02\x80\x01\x00;\x02%[2]d 中の %[1]d 設定をインポートしました。\x02「%[1]s」という名" +
	"前の別の設定が既に存在します。\x02ファイル「%[1]s」は有効な ZIP ファイルではありません。\x02設定「%[1]s」を削除" +
	"\x02設定「%[1]s」を削除してもよろしいですか?\x02新しいクライアント\x02クライアントの編集 - %[1]s\x02基本\x02サ" +
	"ーバーアドレス\x02サーバポート\x02ユーザー\x02STUNサーバー\x02認証\x02認証方法\x02なし\x02トークン\x02秘" +
	"密鍵\x02受信者\x02範囲\x02トークンのURL\x02パラメーター\x02認証\x02接続を維持\x02作業接続\x02ログ\x02" +
	"* ログを記録せず、元のログファイルを削除するには、空白のままにします。\x02ログファイル\x02ログファイルを選択\x02レベル\x02最大" +
	"日数\x02日\x02管理者\x02管理者アドレス\x02パスワード\x02資産\x02管理サーバーがリソースをロードするローカルディレクト" +
	"リを選択します。\x02別のオプション\x02自動削除\x02絶対\x02相対\x02削除日\x02日を削除\x02s\x02接続\x02プ" +
	"ロトコル\x02高度なオプション\x02接続タイムアウト\x02接続を維持\x02アイドルタイムアウト\x02接続プールの数\x02最大スト" +
	"リーム\x02ハートビート\x02間隔\x02タイムアウト\x02有効\x02無効\x02ホスト名\x02証明書\x02証明書ファイルを選択" +
	"\x02証明書キー\x02証明書キーファイルを選択します\x02信頼できる CA\x02信頼できる CA ファイルを選択します\x02カスタムの" +
	"先頭バイトを無効にする\x02高度\x02送信元アドレス\x02多重化\x02ログイン失敗後に終了\x02起動時に自動起動を無効にする" +
	"\x02従来の形式の設定ファイルを使用する\x02メタデータ\x02実験的な機能\x02* 以下の機能はサービスの安定性に影響を与える可能性があ" +
	"ります。\x02サーバーSVCBレコードを使用する\x02HTTP プロキシ\x02UDPパケットサイズ\x02設定はすでに存在します" +
	"\x02設定名「%[1]s」はすでに存在します。\x02プロキシ変換が失敗したため、設定ファイルをアップグレードできません。プロキシ設定を確認し" +
	"て、もう一度試してください。\x0a\x0a不正なプロキシ: %[1]s\x02新しいプロキシ\x02プロキシの編集 - %[1]s\x02" +
	"注釈\x02ランダム\x02タイプ\x02役割\x02サーバ\x02ビジター\x02秘密鍵\x02ローカルアドレス\x02ローカルポート" +
	"\x02リモートポート\x02ユーザーを許可する\x02バインドアドレス\x02バインドポート\x02サーバー名\x02サーバーユーザー\x02" +
	"サブドメイン\x02カスタムドメイン\x02URL ルーティング\x02リクエストヘッダー\x02マルチプレクサ\x02ルートユーザー" +
	"\x02クライアント\x02帯域幅\x02プロキシプロトコル\x02自動\x02既定値\x02トンネルを維持する\x02暗号化\x02圧縮" +
	"\x02代替\x02フォールバックタイムアウト\x02ミリ秒\x02リトライ回数\x02回/時間\x02再試行間隔\x02HTTP ユーザー" +
	"\x02HTTP パスワード\x02ホストの書き換え\x02プラグイン\x02プラグイン名\x02Unix パス\x02Unix パスを選択" +
	"\x02ローカルパス\x02ディレクトリリストのフォルダを選択します。\x02プレフィックスを削除\x02負荷平衡\x02グループ\x02グルー" +
	"プ秘密鍵\x02健康診断\x02タイプ\x02タイムアウト\x02チェック間隔\x02失敗数\x02プロキシはすでに存在します\x02プロキ" +
	"シ名「%[1]s」はすでに存在します。\x02サービス名は必須です。\x02バインドポートは必須です。\x02ローカルポートまたはプラグイン" +
	"が必要です。\x02ローカルアドレスは必須です。\x02ローカルパスは必須です。\x02Unix パスは必須です。\x02ローカルポートが無" +
	"効です。\x02ヘルスチェックのURLは必須です。\x02プラグインは範囲ポートをサポートしていません。\x02無効なリモートポートです。" +
	"\x02ローカル ポートの数はリモート ポートの数と同じである必要があります。\x02カスタム ドメインとサブドメインには、これらのうち少なくと" +
	"も 1 つが設定されている必要があります。\x02ログフォルダを開く\x02最新\x02項目\x02NAT タイプ\x02挙動\x02外部ア" +
	"ドレス\x02はい\x02いいえ\x02公共のネットワーク\x02わからない\x02ランニング\x02停止\x02起動\x02停止\x02状" +
	"態\x02リモートアドレス\x02コピー\x02始める\x02サービス\x02設定「%[1]s」を停止します\x02設定「%[1]s」を停止" +
	"してもよろしいですか?\x02止まる\x02フォルダ\x02ポート\x02ポート開放\x02環境設定\x02マスターパスワード\x02パスワ" +
	"ードを設定して、このプログラムへのアクセスを制限できます。\x0a次回このプログラムを使用するときに入力するよう求められます。\x02マスタ" +
	"ーパスワードを使用する\x02パスワードを変更する\x02言語\x02現在の表示言語は\x02変更を適用するには、プログラムを再起動する必要" +
	"があります。\x02言語を選択する\x02デフォルト\x02新しい設定を作成するときのデフォルト値を定義します。\x0aここでの値は、既存の" +
	"設定には影響しません。\x02デフォルトの設定\x02パスワードが解除されました。\x02新しいマスターパスワード\x02再入力\x02パス" +
	"ワードが設定されています。\x02ログレベル\x02ログ保持\x02クイック追加\x02リモートデスクトップ\x02HTTP ファイルサーバ" +
	"ー\x02無効\x02設定を開く\x02直接編集\x02ドメイン名\x02アクセスアドレスのコピー\x02この機能は、INI または TOM" +
	"L 形式のテキストのみをサポートします。\x02プロキシ「%[1]s」を削除します\x02プロキシ「%[1]s」を削除してもよろしいですか?" +
	"\x02プロキシ「%[1]s」を無効にする\x02プロキシ「%[1]s」を無効にしてもよろしいですか?\x02有効\x02パッシブポート範囲" +
	"\x02FRP マネージャ\x02* バッチインポートをサポートします、1行に1つのリンクがあります。\x02自動的に名前を変更\x02準備" +
	"\x02正しいURLリストを入力してください。\x02ダウンロード\x02パスワードを入力する\x02%[1]s を操作するには、管理パスワード" +
	"を入力する必要があります。\x02管理者パスワードを入力\x02パスワードが正しくありません。 パスワード再入力。\x02無効入力\x02%" +
	".[1]f から %.[2]f までの数字を入力してください。\x02%[1]s から %[2]s までの数値を入力してください。\x02テキス" +
	"トが必要なパターンと一致しません。\x02選択必須\x02提供されたオプションのいずれかを選択してください。\x02選択が必要です。"

var ko_KRIndex = []uint32{ // 274 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000e, 0x00000020, 0x00000035,
	0x00000043, 0x00000051, 0x00000062, 0x00000070,
	0x0000007e, 0x000000a0, 0x000000cb, 0x000000dc,
	0x00000105, 0x00000116, 0x0000013b, 0x0000014d,
	0x00000158, 0x00000172, 0x00000186, 0x0000019a,
	0x000001f3, 0x00000244, 0x00000296, 0x000002cc,
	0x000002d3, 0x000002da, 0x000002e1, 0x000002e5,
	0x000002f2, 0x000002f9, 0x0000030a, 0x00000311,
	// Entry 20 - 3F
	0x0000031c, 0x0000033d, 0x00000358, 0x00000388,
	0x00000395, 0x000003a3, 0x000003b4, 0x000003c5,
	0x000003cc, 0x000003e4, 0x000003f8, 0x00000412,
	0x00000429, 0x00000449, 0x00000454, 0x00000469,
	0x00000492, 0x000004a3, 0x000004b1, 0x000004e5,
	0x00000521, 0x00000559, 0x0000056f, 0x0000059b,
	0x000005af, 0x000005ce, 0x000005db, 0x000005e9,
	0x000005f7, 0x00000601, 0x0000060d, 0x00000614,
	// Entry 40 - 5F
	0x00000622, 0x00000629, 0x00000630, 0x0000063b,
	0x00000649, 0x00000650, 0x0000065b, 0x00000668,
	0x0000066f, 0x0000067a, 0x00000688, 0x00000692,
	0x000006ec, 0x000006fa, 0x0000070f, 0x00000716,
	0x00000724, 0x00000728, 0x00000732, 0x00000743,
	0x00000750, 0x00000757, 0x000007aa, 0x000007b8,
	0x000007c6, 0x000007cd, 0x000007d7, 0x000007e5,
	0x000007f0, 0x000007f2, 0x000007f9, 0x00000800,
	// Entry 60 - 7F
	0x0000080e, 0x00000823, 0x0000082a, 0x0000083f,
	0x0000084a, 0x0000085b, 0x00000868, 0x0000086f,
	0x0000087c, 0x00000883, 0x0000088a, 0x0000089b,
	0x000008a5, 0x000008bd, 0x000008cb, 0x000008e7,
	0x000008ff, 0x00000925, 0x0000094e, 0x00000958,
	0x00000966, 0x00000970, 0x0000098c, 0x000009b2,
	0x000009d8, 0x000009e8, 0x000009f9, 0x00000a49,
	0x00000a63, 0x00000a72, 0x00000a84, 0x00000aa3,
	// Entry 80 - 9F
	0x00000ada, 0x00000b87, 0x00000b95, 0x00000bae,
	0x00000bb5, 0x00000bc2, 0x00000bc9, 0x00000bd0,
	0x00000bd7, 0x00000be1, 0x00000bec, 0x00000bfa,
	0x00000c08, 0x00000c16, 0x00000c27, 0x00000c38,
	0x00000c49, 0x00000c57, 0x00000c68, 0x00000c79,
	0x00000c94, 0x00000ca2, 0x00000cb0, 0x00000cc0,
	0x00000cd1, 0x00000ce1, 0x00000ceb, 0x00000d02,
	0x00000d09, 0x00000d13, 0x00000d21, 0x00000d2b,
	// Entry A0 - BF
	0x00000d32, 0x00000d39, 0x00000d4e, 0x00000d58,
	0x00000d69, 0x00000d74, 0x00000d85, 0x00000d94,
	0x00000da6, 0x00000dba, 0x00000dc7, 0x00000ddb,
	0x00000de7, 0x00000dfa, 0x00000e08, 0x00000e44,
	0x00000e58, 0x00000e66, 0x00000e6d, 0x00000e7f,
	0x00000e8d, 0x00000e94, 0x00000ea2, 0x00000ea9,
	0x00000eb7, 0x00000ed9, 0x00000f13, 0x00000f3f,
	0x00000f64, 0x00000f9a, 0x00000fbc, 0x00000fde,
	// Entry C0 - DF
	0x00000ffe, 0x00001026, 0x0000104c, 0x00001088,
	0x000010b0, 0x000010f2, 0x0000115f, 0x00001174,
	0x0000117b, 0x00001182, 0x0000118d, 0x00001194,
	0x000011a2, 0x000011a6, 0x000011b0, 0x000011c4,
	0x000011d8, 0x000011e2, 0x000011ec, 0x000011f3,
	0x000011fa, 0x00001201, 0x0000120f, 0x00001216,
	0x0000121d, 0x00001227, 0x0000123d, 0x00001269,
	0x00001270, 0x00001284, 0x0000128b, 0x00001299,
	// Entry E0 - FF
	0x000012a0, 0x000012b7, 0x00001373, 0x00001391,
	0x000013a5, 0x000013ac, 0x000013c4, 0x00001410,
	0x0000141e, 0x00001428, 0x000014a0, 0x000014b7,
	0x000014d8, 0x000014f3, 0x0000150a, 0x00001535,
	0x00001543, 0x00001551, 0x0000155f, 0x00001573,
	0x00001586, 0x0000158d, 0x0000159b, 0x000015a9,
	0x000015b3, 0x000015cb, 0x00001611, 0x0000162a,
	0x00001659, 0x00001678, 0x000016ad, 0x000016b4,
	// Entry 100 - 11F
	0x000016cc, 0x000016da, 0x00001723, 0x00001741,
	0x0000174f, 0x00001778, 0x00001785, 0x00001796,
	0x000017dd, 0x000017f8, 0x0000184b, 0x0000185c,
	0x00001894, 0x000018ce, 0x00001907, 0x00001915,
	0x00001948, 0x00001963,
} // Size: 1120 bytes

const ko_KRData string = "" + // Size: 6499 bytes
	"\x02버전: %[1]s\x02FRP 버전: %[1]s\x02빌드 날짜: %[1]s\x02모든 파일\x02구성 파일\x02인증서 " +
	"파일\x02열쇠 파일\x02로그 파일\x02허용 범위를 벗어난 숫자\x02%[1]d보다 큰 숫자를 입력하세요.\x02암호 불일" +
	"치\x02확인하고 다시 시도해 주세요.\x02숫자가 아님\x02유효한 숫자를 입력하세요.\x02새로운 버전!\x02에 대한" +
	"\x02업데이트 다운로드\x02업데이트 확인\x02업데이트 확인\x02의견을 보거나 버그를 보고하려면 프로젝트 페이지를 방문하세요" +
	":\x02FRP 구성 문서를 보려면 FRP 프로젝트 페이지를 방문하십시오:\x02소프트웨어 업데이트를 확인하는 동안 오류가 발생했" +
	"습니다.\x02현재 사용 가능한 업데이트가 없습니다.\x02확인\x02취소\x02이름\x02값\x02추가하다\x02삭제\x02" +
	"모두 지우기\x02구성\x02새 구성\x02파일에서 구성 가져오기\x02구성이 이미 삭제됨\x02\x22%[1]s\x22 구성" +
	"이 이미 제거되었습니다.\x02편집하다\x02파일 열기\x02폴더에 표시\x02복사본 생성\x02모두\x02일반 구성만 해당" +
	"\x02구성 가져오기\x02파일에서 가져오기\x02URL에서 가져오기\x02클립보드에서 가져오기\x02NAT 검색\x02공유 링크" +
	" 복사\x02모든 구성을 ZIP 으로 내보내기\x02구성 만들기\x02수동 설정\x02%[2]d개 구성 중 %[1]d개를 가져왔습" +
	"니다.\x02이름이 \x22%[1]s\x22 인 다른 구성이 이미 있습니다.\x02\x22%[1]s\x22 파일은 유효한 ZI" +
	"P 파일이 아닙니다.\x02\x22%[1]s\x22 구성 삭제\x02\x22%[1]s\x22 구성을 삭제하시겠습니까?\x02새 클" +
	"라이언트\x02클라이언트 편집 - %[1]s\x02기초적인\x02서버 주소\x02서버 포트\x02사용자\x02STUN 서버" +
	"\x02인증\x02인증 방법\x02없음\x02토큰\x02비밀 키\x02받는 사람\x02범위\x02토큰 URL\x02매개변수\x02" +
	"입증\x02대기 중\x02작동 연결\x02통나무\x02* 로그를 기록하지 않고 원본 로그 파일을 삭제하려면 비워 둡니다." +
	"\x02로그 파일\x02로그 파일 선택\x02수준\x02최대 일수\x02날\x02관리자\x02관리자 주소\x02비밀번호\x02자산" +
	"\x02관리 서버가 리소스를 로드할 로컬 디렉토리를 선택하십시오.\x02다른 옵션\x02자동 삭제\x02절대\x02상대적\x02날" +
	"짜 삭제\x02삭제 일\x02s\x02연결\x02규약\x02고급 옵션\x02연결 시간 초과\x02유지\x02유휴 시간 초과" +
	"\x02연결 수\x02최대 스트림\x02심장박동\x02간격\x02타임아웃\x02켜다\x02폐쇄\x02호스트 이름\x02자격증" +
	"\x02인증서 파일 선택\x02인증서 키\x02인증서 키 파일 선택\x02신뢰할 수 있는 CA\x02신뢰할 수 있는 CA 파일 선" +
	"택\x02맞춤 첫 번째 바이트 비활성화\x02고급의\x02소스 주소\x02다중화\x02로그인 실패 후 종료\x02부팅 시 자동" +
	" 시작 비활성화\x02레거시 형식 구성 파일 사용\x02메타데이터\x02실험적 기능\x02* 다음 기능은 서비스의 안정성에 영향을" +
	" 미칠 수 있습니다.\x02서버 SVCB 기록 사용\x02HTTP 프록시\x02UDP 패킷 크기\x02구성이 이미 있습니다." +
	"\x02구성 이름 \x22%[1]s\x22 이(가) 이미 존재합니다.\x02프록시 변환 실패로 인해 구성 파일을 업그레이드할 수 " +
	"없습니다. 프록시 구성을 확인하고 다시 시도하세요.\x0a\x0a잘못된 프록시: %[1]s\x02새 프록시\x02프록시 편집 " +
	"- %[1]s\x02주석\x02무작위의\x02유형\x02역할\x02서버\x02방문객\x02비밀 키\x02지역 주소\x02로컬 포트" +
	"\x02원격 포트\x02사용자 허용\x02바인드 주소\x02바인드 포트\x02서버 이름\x02서버 사용자\x02하위 도메인\x02" +
	"사용자 정의 도메인\x02URL 라우팅\x02요청 헤더\x02멀티플렉서\x02경로 사용자\x02클라이언트\x02대역폭\x02프" +
	"록시 프로토콜\x02자동\x02기본값\x02터널 유지\x02암호화\x02압축\x02폴백\x02대체 시간 초과\x02밀리초" +
	"\x02재시도 횟수\x02회/시간\x02재시도 간격\x02HTTP 사용자\x02HTTP 비밀번호\x02호스트 재작성\x02플러그인" +
	"\x02플러그인 이름\x02Unix 경로\x02선택 Unix 경로\x02로컬 경로\x02디렉토리 목록에 대한 폴더를 선택하십시오." +
	"\x02스트립 접두사\x02부하 분산\x02그룹\x02그룹 비밀 키\x02건강 체크\x02유형\x02시간 초과\x02간격\x02실" +
	"패 횟수\x02프록시가 이미 있습니다.\x02프록시 이름 \x22%[1]s\x22 이(가) 이미 존재합니다.\x02서비스 이름" +
	"은 필수 항목입니다.\x02바인드 포트가 필요합니다.\x02로컬 포트 또는 플러그인이 필요합니다.\x02현지 주소가 필요합니다" +
	".\x02로컬 경로가 필요합니다.\x02Unix 경로가 필요합니다.\x02로컬 포트가 잘못되었습니다.\x02상태 확인 URL이 필" +
	"요합니다.\x02플러그인은 범위 포트를 지원하지 않습니다.\x02원격 포트가 잘못되었습니다.\x02로컬 포트 수는 원격 포트 " +
	"수와 동일해야 합니다.\x02사용자 정의 도메인 및 하위 도메인에는 이러한 세트가 하나 이상 있어야 합니다.\x02로그 폴더 " +
	"열기\x02최신\x02안건\x02NAT 유형\x02행실\x02외부 주소\x02예\x02아니요\x02공용 네트워크\x02알려지지" +
	" 않은\x02달리기\x02중지됨\x02시작\x02멎는\x02상태\x02원격 주소\x02복사\x02시작\x02서비스\x02\x22%" +
	"[1]s\x22 구성 중지\x02\x22%[1]s\x22 구성을 중지하시겠습니까?\x02중지\x02로컬 디렉토리\x02포트\x02" +
	"오픈 포트\x02옵션\x02마스터 비밀번호\x02이 프로그램에 대한 액세스를 제한하기 위해 암호를 설정할 수 있습니다.\x0a" +
	"다음에 이 프로그램을 사용할 때 입력하라는 메시지가 표시됩니다.\x02마스터 비밀번호 사용\x02비밀번호 변경\x02언어" +
	"\x02현재 표시 언어는\x02수정 사항을 적용하려면 프로그램을 재시작해야 합니다.\x02언어 선택\x02기본값\x02새 구성을 " +
	"만들 때 기본값을 정의합니다.\x0a여기의 값은 기존 구성에 영향을 주지 않습니다.\x02기본값으로 설정\x02암호가 제거되었" +
	"습니다.\x02새 마스터 비밀번호\x02비밀번호 재입력\x02비밀번호가 설정되어 있습니다.\x02로그 수준\x02로그 보존" +
	"\x02빠른 추가\x02원격 데스크탑\x02HTTP 파일 서버\x02폐쇄\x02구성 열기\x02직접 편집\x02도메인\x02액세스" +
	" 주소 복사\x02이 기능은 INI 또는 TOML 형식의 텍스트만 지원합니다.\x02프록시 \x22%[1]s\x22 삭제\x02" +
	"\x22%[1]s\x22 프록시를 삭제하시겠습니까?\x02프록시 \x22%[1]s\x22 비활성화\x02\x22%[1]s\x22 " +
	"프록시를 비활성화하시겠습니까?\x02켜다\x02패시브 포트 범위\x02FRP 관리자\x02* 한 줄에 하나의 링크로 일괄 가져" +
	"오기를 지원합니다.\x02자동으로 이름 바꾸기\x02준비가 된\x02올바른 URL 목록을 입력하세요.\x02다운로드\x02암호" +
	"를 입력\x02%[1]s을(를) 작동하려면 관리 암호를 입력해야 합니다.\x02관리 비밀번호 입력\x02비밀번호가 올바르지 않" +
	"습니다. 비밀번호를 다시 입력하세요.\x02잘못된 입력\x02%.[1]f에서 %.[2]f까지의 숫자를 입력하세요.\x02%[1" +
	"]s에서 %[2]s 사이의 숫자를 입력하십시오.\x02텍스트가 필수 패턴과 일치하지 않습니다.\x02선택 필수\x02제공된 옵션 " +
	"중 하나를 선택하십시오.\x02선택이 필요합니다."

var zh_CNIndex = []uint32{ // 274 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000037,
	0x00000044, 0x00000051, 0x0000005e, 0x0000006b,
	0x00000078, 0x00000091, 0x000000ba, 0x000000ca,
	0x000000e0, 0x000000ed, 0x0000010f, 0x0000011f,
	0x00000126, 0x00000133, 0x00000146, 0x00000153,
	0x00000190, 0x000001ce, 0x000001ed, 0x0000020c,
	0x00000213, 0x0000021a, 0x00000221, 0x00000225,
	0x0000022c, 0x00000233, 0x00000240, 0x00000247,
	// Entry 20 - 3F
	0x00000254, 0x0000026a, 0x0000027a, 0x0000029b,
	0x000002a2, 0x000002af, 0x000002c5, 0x000002d2,
	0x000002d9, 0x000002e9, 0x000002f6, 0x00000306,
	0x00000315, 0x00000328, 0x00000333, 0x00000346,
	0x00000369, 0x00000376, 0x00000383, 0x000003b6,
	0x000003e6, 0x00000414, 0x0000042c, 0x0000046b,
	0x0000047b, 0x00000493, 0x0000049a, 0x000004aa,
	0x000004ba, 0x000004c4, 0x000004d0, 0x000004d7,
	// Entry 40 - 5F
	0x000004e4, 0x000004e8, 0x000004ef, 0x000004f6,
	0x00000500, 0x0000050a, 0x00000517, 0x0000051e,
	0x00000525, 0x00000532, 0x0000053f, 0x00000546,
	0x00000585, 0x00000592, 0x000005a5, 0x000005ac,
	0x000005b9, 0x000005bd, 0x000005c4, 0x000005d1,
	0x000005d8, 0x000005e5, 0x00000619, 0x00000626,
	0x00000633, 0x0000063a, 0x00000641, 0x0000064e,
	0x0000065b, 0x0000065f, 0x00000666, 0x0000066d,
	// Entry 60 - 7F
	0x0000067a, 0x00000687, 0x00000694, 0x000006a1,
	0x000006b1, 0x000006c1, 0x000006c8, 0x000006cf,
	0x000006d6, 0x000006dd, 0x000006e4, 0x000006f1,
	0x000006fe, 0x00000711, 0x0000071e, 0x00000737,
	0x00000747, 0x00000760, 0x00000779, 0x00000780,
	0x00000790, 0x0000079d, 0x000007b9, 0x000007cf,
	0x000007eb, 0x000007f5, 0x00000805, 0x00000838,
	0x00000854, 0x00000860, 0x0000086e, 0x0000087e,
	// Entry 80 - 9F
	0x0000089f, 0x00000916, 0x00000923, 0x00000938,
	0x0000093f, 0x0000094c, 0x00000953, 0x0000095a,
	0x00000964, 0x0000096e, 0x00000975, 0x00000982,
	0x0000098f, 0x0000099c, 0x000009a9, 0x000009b6,
	0x000009c3, 0x000009d0, 0x000009dd, 0x000009e7,
	0x000009f7, 0x00000a02, 0x00000a0c, 0x00000a16,
	0x00000a23, 0x00000a2d, 0x00000a3a, 0x00000a47,
	0x00000a4e, 0x00000a55, 0x00000a62, 0x00000a6f,
	// Entry A0 - BF
	0x00000a7c, 0x00000a83, 0x00000a90, 0x00000a97,
	0x00000aa4, 0x00000aaf, 0x00000abc, 0x00000ac8,
	0x00000ad4, 0x00000ae0, 0x00000ae7, 0x00000af4,
	0x00000b00, 0x00000b13, 0x00000b20, 0x00000b4e,
	0x00000b5b, 0x00000b68, 0x00000b75, 0x00000b82,
	0x00000b8f, 0x00000b9c, 0x00000ba9, 0x00000bb6,
	0x00000bc3, 0x00000bd3, 0x00000bf4, 0x00000c10,
	0x00000c2c, 0x00000c51, 0x00000c6d, 0x00000c89,
	// Entry C0 - DF
	0x00000ca5, 0x00000cbe, 0x00000cdf, 0x00000cfe,
	0x00000d17, 0x00000d51, 0x00000d8b, 0x00000da1,
	0x00000da8, 0x00000daf, 0x00000dba, 0x00000dc1,
	0x00000dce, 0x00000dd2, 0x00000dd6, 0x00000ddd,
	0x00000de4, 0x00000df1, 0x00000dfb, 0x00000e08,
	0x00000e15, 0x00000e1c, 0x00000e29, 0x00000e30,
	0x00000e37, 0x00000e3e, 0x00000e56, 0x00000e7d,
	0x00000e84, 0x00000e91, 0x00000e98, 0x00000ea5,
	// Entry E0 - FF
	0x00000eac, 0x00000eb6, 0x00000f24, 0x00000f34,
	0x00000f41, 0x00000f48, 0x00000f5e, 0x00000f8f,
	0x00000f9c, 0x00000fa6, 0x00000ff6, 0x00001006,
	0x00001019, 0x00001026, 0x00001033, 0x00001046,
	0x00001053, 0x00001060, 0x0000106d, 0x0000107a,
	0x0000108c, 0x00001093, 0x000010a6, 0x000010b3,
	0x000010ba, 0x000010cd, 0x00001100, 0x00001118,
	0x0000113f, 0x00001157, 0x0000117e, 0x00001185,
	// Entry 100 - 11F
	0x00001198, 0x000011a6, 0x000011d3, 0x000011e3,
	0x000011f0, 0x00001211, 0x00001218, 0x00001225,
	0x00001253, 0x00001266, 0x00001288, 0x00001295,
	0x000012c7, 0x000012f7, 0x0000131c, 0x00001326,
	0x00001345, 0x00001355,
} // Size: 1120 bytes

const zh_CNData string = "" + // Size: 4949 bytes
	"\x02版本：%[1]s\x02FRP 版本：%[1]s\x02构建日期：%[1]s\x02所有文件\x02配置文件\x02证书文件\x02密钥" +
	"文件\x02日志文件\x02数值超出允许范围\x02请输入一个大于 %[1]d 的数字。\x02密码不匹配\x02请检查并重试。\x02不是" +
	"数字\x02请输入一个有效的数字。\x02发现更新！\x02关于\x02下载更新\x02正在检查更新\x02检查更新\x02如有任何意见或报" +
	"告错误，请访问项目地址：\x02了解 FRP 软件配置文档，请访问 FRP 项目地址：\x02检查更新时出现错误。\x02当前没有可用的更新" +
	"。\x02确定\x02取消\x02名称\x02值\x02添加\x02删除\x02全部清除\x02配置\x02新建配置\x02从文件导入配置" +
	"\x02配置已删除\x02配置名「%[1]s」已删除。\x02编辑\x02打开文件\x02在文件夹中显示\x02创建副本\x02全部\x02仅通" +
	"用配置\x02导入配置\x02从文件导入\x02从 URL 导入\x02从剪贴板导入\x02NAT 检测\x02复制分享链接\x02导出所有" +
	"配置 (ZIP 压缩包)\x02新建配置\x02手动设置\x02导入了 %[2]d 个配置文件中的 %[1]d 个。\x02另一个同名的配置" +
	"「%[1]s」已存在。\x02文件 \x22%[1]s\x22 不是有效的压缩文件。\x02删除配置「%[1]s」\x02确定要删除配置「%" +
	"[1]s」吗？此操作无法撤销。\x02新建客户端\x02编辑客户端 - %[1]s\x02基本\x02服务器地址\x02服务器端口\x02用户名" +
	"\x02STUN 服务\x02认证\x02认证方式\x02无\x02令牌\x02密钥\x02接收者\x02作用域\x02令牌地址\x02参数" +
	"\x02鉴权\x02心跳消息\x02工作连接\x02日志\x02* 留空则不记录日志，且删除原来的日志文件。\x02日志文件\x02选择日志文件" +
	"\x02级别\x02最大天数\x02天\x02管理\x02管理地址\x02密码\x02静态资源\x02选择管理服务器使用的静态资源目录。\x02" +
	"其他选项\x02自动删除\x02绝对\x02相对\x02删除日期\x02删除天数\x02秒\x02连接\x02协议\x02高级选项\x02连" +
	"接超时\x02保活周期\x02闲置超时\x02连接池数量\x02最大流数量\x02心跳\x02间隔\x02超时\x02开启\x02关闭" +
	"\x02主机名称\x02证书文件\x02选择证书文件\x02密钥文件\x02选择证书密钥文件\x02受信任证书\x02选择受信任的证书\x02禁" +
	"用自定义首字节\x02高级\x02使用源地址\x02多路复用\x02初次登录失败后退出\x02禁用开机自启动\x02使用旧格式配置文件" +
	"\x02元数据\x02实验性功能\x02* 以下功能可能会影响服务的稳定性。\x02使用服务器 SVCB 记录\x02HTTP 代理\x02UD" +
	"P 包大小\x02配置已存在\x02配置名「%[1]s」已存在。\x02由于代理转换失败，无法升级您的配置文件，请检查代理配置并重试。\x0a" +
	"\x0a出错的代理：%[1]s\x02新建代理\x02编辑代理 - %[1]s\x02注释\x02随机名称\x02类型\x02角色\x02服务端" +
	"\x02访问者\x02私钥\x02本地地址\x02本地端口\x02远程端口\x02允许用户\x02绑定地址\x02绑定端口\x02服务名称" +
	"\x02服务用户\x02子域名\x02自定义域名\x02URL 路由\x02请求头\x02复用器\x02路由用户\x02客户端\x02带宽限流" +
	"\x02代理协议\x02自动\x02默认\x02隧道保活\x02加密传输\x02压缩传输\x02备用\x02备用超时\x02毫秒\x02重试次数" +
	"\x02次/小时\x02重试间隔\x02HTTP 用户\x02HTTP 密码\x02Host 替换\x02插件\x02插件名称\x02Unix " +
	"路径\x02选择 Unix 路径\x02本地路径\x02选择需要显示目录列表的文件夹。\x02移除前缀\x02负载均衡\x02分组名称" +
	"\x02分组密钥\x02健康检查\x02检查类型\x02检查超时\x02检查周期\x02错误次数\x02代理已存在\x02代理名「%[1]s」已" +
	"存在。\x02必须填写服务名称。\x02必须填写绑定端口。\x02必须填写本地端口或插件。\x02必须填写本地地址。\x02必须填写本地路径" +
	"。\x02必须填写 Unix 路径。\x02无效的本地端口。\x02健康检查 URL 为必填项。\x02插件不支持范围端口。\x02无效的远" +
	"程端口。\x02本地端口的数量应与远程端口的数量相同。\x02自定义域名和子域名应至少填写其中之一。\x02打开日志文件夹\x02最新" +
	"\x02项目\x02NAT 类型\x02行为\x02外部地址\x02是\x02否\x02公网\x02未知\x02正在运行\x02已停止\x02正" +
	"在启动\x02正在停止\x02状态\x02远程地址\x02复制\x02启动\x02服务\x02停止配置「%[1]s」\x02确定要停止配置「" +
	"%[1]s」吗？\x02停止\x02本地目录\x02端口\x02打开端口\x02选项\x02主密码\x02您可以设置密码来限制访问此程序。" +
	"\x0a在下次使用此程序时，您将被要求输入密码。\x02使用主密码\x02修改密码\x02语言\x02目前的显示语言\x02您必须重新启动程序才" +
	"能应用修改。\x02选择语言\x02默认值\x02定义新建配置时的默认值。\x0a此处的值不会影响现有的配置。\x02设置默认值\x02密码" +
	"已删除。\x02新主密码\x02确认密码\x02密码已设定。\x02日志级别\x02日志保留\x02快速添加\x02远程桌面\x02HTTP" +
	" 文件服务\x02禁用\x02打开配置文件\x02直接编辑\x02域名\x02复制访问地址\x02此功能仅支持 INI 或 TOML 格式的文本" +
	"。\x02删除代理「%[1]s」\x02确定要删除代理「%[1]s」吗？\x02禁用代理「%[1]s」\x02确定要禁用代理「%[1]s」吗" +
	"？\x02启用\x02被动端口范围\x02FRP 管理器\x02* 支持批量导入，每行一个链接。\x02自动重命名\x02准备就绪\x02请" +
	"输入正确的 URL 列表。\x02下载\x02输入密码\x02您必须输入管理密码来使用 %[1]s。\x02输入管理密码\x02密码错误。请" +
	"重新输入。\x02输入无效\x02请输入一个从 %.[1]f 到 %.[2]f 的数字。\x02请输入一个从 %[1]s 到 %[2]s 的" +
	"数字。\x02文本与要求的模式不匹配。\x02必填项\x02请选择其中一个选项。\x02需要选择。"

var zh_TWIndex = []uint32{ // 274 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000037,
	0x00000044, 0x00000051, 0x0000005e, 0x0000006b,
	0x00000078, 0x00000091, 0x000000ba, 0x000000ca,
	0x000000e0, 0x000000ed, 0x0000010f, 0x0000011f,
	0x00000126, 0x00000133, 0x00000146, 0x00000153,
	0x00000190, 0x000001ce, 0x000001ed, 0x0000020c,
	0x00000213, 0x0000021a, 0x00000221, 0x00000225,
	0x0000022c, 0x00000233, 0x00000240, 0x00000247,
	// Entry 20 - 3F
	0x00000254, 0x0000026a, 0x0000027a, 0x0000029b,
	0x000002a2, 0x000002af, 0x000002c5, 0x000002d2,
	0x000002d9, 0x000002e9, 0x000002f6, 0x00000306,
	0x00000315, 0x00000328, 0x00000333, 0x00000346,
	0x00000369, 0x00000376, 0x00000383, 0x000003b6,
	0x000003e6, 0x00000414, 0x0000042c, 0x0000046b,
	0x0000047b, 0x00000493, 0x0000049a, 0x000004aa,
	0x000004ba, 0x000004c4, 0x000004d0, 0x000004d7,
	// Entry 40 - 5F
	0x000004e4, 0x000004e8, 0x000004ef, 0x000004f6,
	0x00000500, 0x0000050a, 0x00000517, 0x0000051e,
	0x00000525, 0x00000532, 0x0000053f, 0x00000546,
	0x00000585, 0x00000592, 0x000005a5, 0x000005ac,
	0x000005b9, 0x000005bd, 0x000005c4, 0x000005d1,
	0x000005d8, 0x000005e5, 0x00000619, 0x00000626,
	0x00000633, 0x0000063a, 0x00000641, 0x0000064e,
	0x0000065b, 0x0000065f, 0x00000666, 0x0000066d,
	// Entry 60 - 7F
	0x0000067a, 0x00000687, 0x00000694, 0x000006a1,
	0x000006b1, 0x000006c1, 0x000006c8, 0x000006cf,
	0x000006d6, 0x000006dd, 0x000006e4, 0x000006f1,
	0x000006fe, 0x00000711, 0x0000071e, 0x00000737,
	0x00000747, 0x00000760, 0x00000776, 0x0000077d,
	0x0000078d, 0x0000079a, 0x000007b6, 0x000007cc,
	0x000007e5, 0x000007ef, 0x000007ff, 0x00000832,
	0x0000084e, 0x0000085a, 0x00000868, 0x00000878,
	// Entry 80 - 9F
	0x00000899, 0x00000910, 0x0000091d, 0x00000932,
	0x00000939, 0x00000946, 0x0000094d, 0x00000954,
	0x0000095e, 0x00000968, 0x0000096f, 0x0000097c,
	0x00000989, 0x00000996, 0x000009a3, 0x000009b0,
	0x000009bd, 0x000009ca, 0x000009d7, 0x000009e1,
	0x000009f1, 0x000009fc, 0x00000a06, 0x00000a10,
	0x00000a1d, 0x00000a27, 0x00000a34, 0x00000a41,
	0x00000a48, 0x00000a4f, 0x00000a5c, 0x00000a69,
	// Entry A0 - BF
	0x00000a76, 0x00000a7d, 0x00000a8a, 0x00000a91,
	0x00000a9e, 0x00000aa9, 0x00000ab6, 0x00000ac2,
	0x00000ace, 0x00000ada, 0x00000ae1, 0x00000aee,
	0x00000afa, 0x00000b0d, 0x00000b1a, 0x00000b48,
	0x00000b55, 0x00000b62, 0x00000b6f, 0x00000b7c,
	0x00000b89, 0x00000b96, 0x00000ba3, 0x00000bb0,
	0x00000bbd, 0x00000bcd, 0x00000bee, 0x00000c0a,
	0x00000c26, 0x00000c4b, 0x00000c67, 0x00000c83,
	// Entry C0 - DF
	0x00000c9f, 0x00000cb8, 0x00000cd9, 0x00000cf8,
	0x00000d11, 0x00000d4b, 0x00000d82, 0x00000d98,
	0x00000d9f, 0x00000da6, 0x00000db1, 0x00000db8,
	0x00000dc5, 0x00000dc9, 0x00000dcd, 0x00000dd4,
	0x00000ddb, 0x00000de8, 0x00000df2, 0x00000dff,
	0x00000e0c, 0x00000e13, 0x00000e20, 0x00000e27,
	0x00000e2e, 0x00000e35, 0x00000e4d, 0x00000e74,
	0x00000e7b, 0x00000e88, 0x00000e8f, 0x00000e9c,
	// Entry E0 - FF
	0x00000ea3, 0x00000ead, 0x00000f1b, 0x00000f2b,
	0x00000f38, 0x00000f3f, 0x00000f55, 0x00000f86,
	0x00000f93, 0x00000f9d, 0x00000fed, 0x00000ffd,
	0x00001010, 0x0000101d, 0x0000102a, 0x0000103d,
	0x0000104a, 0x00001057, 0x00001064, 0x00001071,
	0x00001083, 0x0000108a, 0x0000109d, 0x000010aa,
	0x000010b1, 0x000010c4, 0x000010f7, 0x0000110f,
	0x00001136, 0x0000114e, 0x00001175, 0x0000117c,
	// Entry 100 - 11F
	0x0000118f, 0x0000119d, 0x000011ca, 0x000011da,
	0x000011e7, 0x00001208, 0x0000120f, 0x0000121c,
	0x0000124a, 0x0000125d, 0x0000127f, 0x0000128c,
	0x000012be, 0x000012ee, 0x00001313, 0x0000131d,
	0x0000133c, 0x0000134c,
} // Size: 1120 bytes

const zh_TWData string = "" + // Size: 4940 bytes
	"\x02版本：%[1]s\x02FRP 版本：%[1]s\x02構建日期：%[1]s\x02所有文件\x02配置文件\x02證書文件\x02密鑰" +
	"文件\x02日誌文件\x02數值超出允許範圍\x02請輸入一個大於 %[1]d 的數字。\x02密碼不匹配\x02請檢查並重試。\x02不是" +
	"數字\x02請輸入一個有效的數字。\x02發現更新！\x02關於\x02下載更新\x02正在檢查更新\x02檢查更新\x02如有任何意見或報" +
	"告錯誤，請訪問項目地址：\x02了解 FRP 軟件配置文檔，請訪問 FRP 項目地址：\x02檢查更新時出現錯誤。\x02當前沒有可用的更新" +
	"。\x02確定\x02取消\x02名稱\x02值\x02添加\x02刪除\x02全部清除\x02配置\x02新建配置\x02從文件導入配置" +
	"\x02配置已刪除\x02配置名「%[1]s」已刪除。\x02編輯\x02打開文件\x02在文件夾中顯示\x02創建副本\x02全部\x02僅通" +
	"用配置\x02導入配置\x02從文件導入\x02從 URL 導入\x02從剪貼板導入\x02NAT 檢測\x02復制分享鏈接\x02導出所有" +
	"配置 (ZIP 壓縮包)\x02新建配置\x02手動設置\x02導入了 %[2]d 個配置文件中的 %[1]d 個。\x02另一個同名的配置" +
	"「%[1]s」已存在。\x02文件 \x22%[1]s\x22 不是有效的壓縮文件。\x02刪除配置「%[1]s」\x02確定要刪除配置「%" +
	"[1]s」嗎？此操作無法撤銷。\x02新建客戶端\x02編輯客戶端 - %[1]s\x02基本\x02服務器地址\x02服務器端口\x02用戶名" +
	"\x02STUN 服務\x02認證\x02認證方式\x02無\x02令牌\x02密鑰\x02接收者\x02作用域\x02令牌地址\x02參數" +
	"\x02鑑權\x02心跳消息\x02工作連接\x02日誌\x02* 留空則不記錄日誌，且刪除原來的日誌文件。\x02日誌文件\x02選擇日誌文件" +
	"\x02級別\x02最大天數\x02天\x02管理\x02管理地址\x02密碼\x02靜態資源\x02選擇管理服務器使用的靜態資源目錄。\x02" +
	"其他選項\x02自動刪除\x02絕對\x02相對\x02刪除日期\x02刪除天數\x02秒\x02連接\x02協議\x02進階選項\x02連" +
	"接超時\x02保活週期\x02閒置超時\x02連接池數量\x02最大流數量\x02心跳\x02間隔\x02超時\x02開啟\x02關閉" +
	"\x02主機名稱\x02證書文件\x02選擇證書文件\x02密鑰文件\x02選擇證書密鑰文件\x02受信任證書\x02選擇受信任的證書\x02停" +
	"用自訂首字節\x02高級\x02使用源地址\x02多路復用\x02初次登錄失敗後退出\x02禁用開機自啟動\x02使用舊格式設定檔\x02元" +
	"數據\x02實驗性功能\x02* 以下功能可能會影響服務的穩定性。\x02使用服務器 SVCB 記錄\x02HTTP 代理\x02UDP 包" +
	"大小\x02配置已存在\x02配置名「%[1]s」已存在。\x02由於代理轉換失敗，無法升級您的配置文件，請檢查代理配置並重試。\x0a" +
	"\x0a出錯的代理：%[1]s\x02新建代理\x02編輯代理 - %[1]s\x02註解\x02隨機名稱\x02類型\x02角色\x02服務端" +
	"\x02訪問者\x02私鑰\x02本地地址\x02本地端口\x02遠程端口\x02允許用戶\x02綁定地址\x02綁定端口\x02服務名稱" +
	"\x02服務用戶\x02子域名\x02自定義域名\x02URL 路由\x02請求頭\x02復用器\x02路由用戶\x02客戶端\x02帶寬限流" +
	"\x02代理協議\x02自動\x02默認\x02隧道保活\x02加密傳輸\x02壓縮傳輸\x02備用\x02備用超時\x02毫秒\x02重試次數" +
	"\x02次/小時\x02重試間隔\x02HTTP 用戶\x02HTTP 密碼\x02Host 替換\x02插件\x02插件名稱\x02Unix " +
	"路徑\x02選擇 Unix 路徑\x02本地路徑\x02選擇需要顯示目錄列表的文件夾。\x02移除前綴\x02負載均衡\x02分組名稱" +
	"\x02分組密鑰\x02健康檢查\x02檢查類型\x02檢查超時\x02檢查週期\x02錯誤次數\x02代理已存在\x02代理名「%[1]s」已" +
	"存在。\x02必須填寫服務名稱。\x02必須填寫綁定端口。\x02必須填寫本地端口或插件。\x02必須填寫本地地址。\x02必須填寫本地路徑" +
	"。\x02必須填寫 Unix 路徑。\x02無效的本地端口。\x02健康檢查 URL 為必填項。\x02插件不支援範圍端口。\x02無效的遠" +
	"端端口。\x02本地端口的數量應與遠端端口的數量相同。\x02自訂網域和子網域應至少填寫其中之一。\x02打開日誌文件夾\x02最新\x02" +
	"項目\x02NAT 類型\x02行為\x02外部地址\x02是\x02否\x02公網\x02未知\x02正在運行\x02已停止\x02正在啟" +
	"動\x02正在停止\x02狀態\x02遠程地址\x02複製\x02啟動\x02服務\x02停止配置「%[1]s」\x02確定要停止配置「%[" +
	"1]s」嗎？\x02停止\x02本地目錄\x02端口\x02打開端口\x02選項\x02主密碼\x02您可以設置密碼來限制訪問此程式。\x0a在" +
	"下次使用此程式時，您將被要求輸入密碼。\x02使用主密碼\x02修改密碼\x02語言\x02目前的顯示語言\x02您必須重新啟動程式才能應用" +
	"修改。\x02選擇語言\x02默認值\x02定義新建配置時的默認值。\x0a此處的值不會影響現有的配置。\x02設置默認值\x02密碼已刪除" +
	"。\x02新主密碼\x02確認密碼\x02密碼已設定。\x02日誌級別\x02日誌保留\x02快速添加\x02遠程桌面\x02HTTP 文件" +
	"服務\x02禁用\x02打開配置文件\x02直接編輯\x02域名\x02複製訪問地址\x02此功能僅支援 INI 或 TOML 格式的文字。" +
	"\x02刪除代理「%[1]s」\x02確定要刪除代理「%[1]s」嗎？\x02禁用代理「%[1]s」\x02確定要禁用代理「%[1]s」嗎？" +
	"\x02啟用\x02被動端口範圍\x02FRP 管理器\x02* 支持批量導入，每行一個鏈接。\x02自動重命名\x02準備就緒\x02請輸入正" +
	"確的 URL 列表。\x02下載\x02輸入密碼\x02您必須輸入管理密碼來使用 %[1]s。\x02輸入管理密碼\x02密碼錯誤。請重新輸" +
	"入。\x02輸入無效\x02請輸入一個從 %.[1]f 到 %.[2]f 的數字。\x02請輸入一個從 %[1]s 到 %[2]s 的數字。" +
	"\x02文本與要求的模式不匹配。\x02必填項\x02請選擇其中一個選項。\x02需要選擇。"

	// Total table size 42672 bytes (41KiB); checksum: 96645174
