name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  golangci:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61
